name: Ping Render Backend

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render URL
        run: curl -fsS https://fastapi-nn-backend.onrender.com/keep-alive
